apiVersion: batch/v1
kind: CronJob
metadata:
  name: spring-boot-api-caller-cronjob
spec:
  schedule: "*/5 * * * *"  # This schedule runs the job every 5 minutes
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: spring-boot-k8s
        spec:
          containers:
            - name: spring-boot-api-caller
              image: springboot-k8s-example:1.0  # Replace with your actual image
              command: ["/bin/sh", "-c"]
              args:
                - curl -X GET "https://www.googleapis.com/books/v1/volumes?q=isbn:9780140328721"
          restartPolicy: OnFailure
