apiVersion: batch/v1
kind: CronJob
metadata:
  name: reporting-job
spec:
  schedule: "*/3 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scheduler-job
              image: springboot-k8s-example:1.0
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure